### PR TITLE
Remove ISeekable from Else/ElseError

### LINKED ISSUE #215: Different ZeroOrOne behavior in 1.3.6
I am using `ElseError` method to provide targeted error messages for each sub-parser.
This was working fine, until I upgraded to 1.3.6 release.
Perhaps I am doing something wrong since the beginning, but here is the code that was working before and now it throws a `ParseException`.
Is there something I should change on my code or is this a bug?

```csharp
private abstract class NodeBase
{
}

private class BasicNode : NodeBase
{
    public BasicNode(string value)
    {
        Value = value;
    }

    public string Value { get; }
}

private class CombinedNode : NodeBase
{
    public CombinedNode(NodeBase left, NodeBase right)
    {
        Left = left;
        Right = right;
    }

    NodeBase Left { get; }

    NodeBase Right { get; }
}

[Fact]
public void ParseTest()
{
    Parser<char> leftParenthesis = Terms.Char('(');
    Parser<char> rightParenthesis = Terms.Char(')');

    Parser<string> quotedText = Terms.String()
        .Then(t => t.Span.ToString());

    Parser<NodeBase> identifier = ZeroOrOne(
        quotedText.Then<NodeBase>(s => new BasicNode(s))
            .ElseError("Invalid expression with identifier"));

    Deferred<NodeBase> expression = Deferred<NodeBase>();

    Parser<NodeBase> factor = ZeroOrOne(
       Between(leftParenthesis, expression, rightParenthesis)
           .ElseError("Invalid expression with parenthesis"));

    Parser<NodeBase> operand = factor
        .Or(identifier)
        .ElseError("Invalid expression");

    Parser<string> and = Terms.Text("and", caseInsensitive: true);
    Parser<string> or = Terms.Text("or", caseInsensitive: true);

    Parser<NodeBase> term = ZeroOrOne(
        operand.LeftAssociative(
            (and, static (left, right) => new CombinedNode(left, right)))
                .ElseError("Invalid expression with AND operator"));

    expression.Parser = ZeroOrOne(
        term.LeftAssociative(
            (or, static (left, right) => new CombinedNode(left, right)))
                .ElseError("Invalid expression with OR operator"));

    NodeBase? actual = expression.Eof().Parse("'Test'");

    actual.Should().NotBeNull();
    actual.Should().BeOfType<BasicNode>();
}


```

### PR DESCRIPTION
**Pull request by sebastienros**
Fixes #215

### CODE REVIEW

File: src/Parlot/Fluent/Else.cs [hunk 1]
```diff
@@ -1,34 +1,20 @@
 using Parlot.Compilation;
-using Parlot.Rewriting;
 using System.Linq.Expressions;
 
 namespace Parlot.Fluent;
 
 /// <summary>
 /// Returns a default value if the previous parser failed.
 /// </summary>
-public sealed class Else<T> : Parser<T>, ICompilable, ISeekable
```
Comment (hishamco) [inline src/Parlot/Fluent/Else.cs:10]: This is a breaking change

File: src/Parlot/Fluent/Error.cs [hunk 2]
```diff
@@ -8,28 +8,15 @@
 
 namespace Parlot.Fluent;
 
-public sealed class ElseError<T> : Parser<T>, ICompilable, ISeekable
```
Comment (hishamco) [inline src/Parlot/Fluent/Error.cs:11]: This is a breaking change

Comment (sebastienros) [reply src/Parlot/Fluent/Error.cs:11]: This is a marker class, doesn't matter.

Comment (hishamco) [reply src/Parlot/Fluent/Error.cs:11]: While it's a public API it's a breaking-change :)
